ifeq ($(MAKELEVEL),0)
default: sticky
sticky: clearerror
	$(MAKE) $(MAKEOPTS) .  BOOT=nonBOOT  LIBRARY=slave_routing  FREQUENCY=EU  CODE_MEMORY_MODE=banking  SENSOR_TYPE=BATTERY  CHIP=ZW050x  WATCHDOG=WATCHDOG_ENABLED
else
default: ZW0x0x
endif
#
STICKY_TARGET:=yes
